





  jwt:
    header: Authorization
    prefix: Bearer
    accessExpiration: 3600
    refreshExpiration: 604800
    secretKey: 123456789123456789123456789123456789123456789
    teacherSecret: ccc
    studentSecret: ddd

  jackson:
    property-naming-strategy: SNAKE_CASE

  redis:
    host: localhost
    port: 6379
